(package "sound-async" 
         "0.1.0" 
         "Play sound asynchronously")

(website-url "https://github.com/jcs-elpa/sound-async")
(keywords "multimedia")

(package-file "sound-async.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "async")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
